# This is a basic workflow to help you get started with Actions

name: stm32l5

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: mbed build
        uses: addnab/docker-run-action@v3
        with:
          options: -v ${{ github.workspace }}:/work -w=/work
          image: mbedos/mbed-os-env:latest
          shell: bash
          run: |
              git clone https://${{ secrets.SYNC_MBED }}:x-oauth-basic@github.com/jeromecoutant/mbed.git mbed-os
              cd mbed-os
              git checkout origin/DEV_TFM -b ACTIONS -f
              cd ..
              # apt update && apt install sudo
              # sudo apt-get install srecord -y
              apt update
              apt install srecord -y
              python3 build_tfm.py -m NUCLEO_L552ZE_Q -t GNUARM -c RegressionIPC
              cd mbed-os
              git config user.email "jerome.coutant@st.com"
              git config  user.name "jeromecoutant"
              echo git commit -am "TFM bin"
              git commit -am "TFM bin"
              echo git push origin HEAD -f
              git push origin HEAD -f
